### ISSUE TITLE
Certain Sierra Leone Demo Datasets do not load on Android DC

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-datacapture#44]
(Tested on an Android 4.4.4)

Certain Sierra Leone demo Data Sets fail to load on Android (they just present the blank screen captured in the screenshot below), but work well (with the same user) on the web Data Entry app. They include:
ART monthly summary
EPI stock
Inpatient morbidity/mortality summary
Life-saving commodities
It's difficult to find the pattern here - Emma originally reported Attribute CatCombos as the possible issue, but one of the Data Sets has no Attribute CatCombos. I can get two Data Sets to load by deleting compulsory data elements (EPI and ART Monthly Summary), but the other two Data Sets don't have any compulsory data elements...
Is it possible that either (1) there are two different bugs resulting in the same blank screen or (2) it's something deeper, such as problems with legacy database records originally written in an earlier version, and certain changes to metadata (eg changing compulsory data elements) rewrites these database records, thereby fixing the problem...?

**Comment by idelcano** [comment]
@xurxodev you need review this issue, we still had some problems

Is necessary use the user Android:Android123 instead of admin.

1. Missing dataelements in api responses:

The api call is filtering the field forms by Orgunit, and when a categoryOption is not assigned to the active orgunit the api not creates the dataelement with this categoryoption.
I think the dataentry is not filtering the dataelement+categoryoption by orgunits in the web side.

We can fix it changing the permissions on the server, but is a heavy work, and a api call not filtered by orgunit be better.

You can look how works with this calls:
The dataElement is a list of a dataelements in combination with the categoryComboOptions.

https://play.dhis2.org/android-previous1/api/dataSets/pBOMPrpg1QX/form.json?ou=O6uvpzGd5pu&pe=201709
Other call:
https://play.dhis2.org/android-previous1/api/dataSets/TuL8IOPzpHh/form.json?ou=DiszpKrYNg8&pe=201705&categoryOptions=[i4Nbp8S2G6A]
The categoryOption fields doesn't nothing


2. Blank pages:

We could not replicate this. 
In some strange situation when you open a dataset the dataset is a blank page. You only can solve this problem after closing and re-opening the app.

Manu pulled some files of the app with this problem. 
I will send you it in a email, but the more relevant of that files is:
 optionset folder not exists and dataset fields are empty.


The problem happens in the method removeFieldsWithInvalidCategoryOptionRelation.
This method removes all the fields in this strange situation.
I had this problem one time, and debugging the app the fields was removed in this point:
	(Line 114 file DataSetMetaData)
	
1		if (categoryComboByDataElement.get(field.getDataElement()) == null) {
2            if (isValidDefaultField(field, dataSetCategoryOptions)) return true;
3            if (isValidSectionField(field, section, categoryOptionComboBySection)) return true;
4        } else if (isAValidCategoryOptionCombo(categoryComboByDataElement, field)) {
5            return true;
6        }
7        return false;

In this case, the dataset should go to the 4 line.
But for any reason the map of categoryComboByDataElements has the correct keys with all the form fields, in relationship with a null categorycombouid list (line 1).

And the dataset don't have default field(line 2) or section fields(line 3) and all fields returns false.
All the fields are null, and will be removed in this case.

**Comment by ifoche** [comment]
After some test, I've finally found this is a server error. It has to do with legends and sections, and I will explain it later in a more detailed comment

**Comment by ifoche** [comment]
Just for the record. We had 2 problems on this issue:
1) Blanks when opening a dataSet. This is a server issue.
- The server seems to be using a previous DB with wrong references that generate an invalid dataSet API answer. 
- To make it work, only by removing the legend attached to those DataSets, it looks like the server is then readjusting and validating the references in the background and then it make the app work again. 
- Once the server has readjusted its references, the server continues working even if you select back the legend in the dataSet.

2) DataSets that couldn't be opened. This is also a server issue.
- The reason why those dataSets cannot be opened is because some categories in the category combination configured in the dataSet are not displayed. and cannot be selected, so the dataSet cannot be opened. 
- The behavior between the server and the android app is exactly the same. Server side the category name is shown but there are no category options and the data cannot be entered
